// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VA.API.Data;

#nullable disable

namespace VA.API.Migrations.CustomerDb;

[DbContext(typeof(CustomerContext))]
partial class CustomerContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

        modelBuilder.Entity("VA.API.Models.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<string>("CustomerCode")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("CustomerName")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Customers");

                b.HasData(
                    new
                    {
                        Id = new Guid("e455f48f-35d1-4fa4-aaf1-4f7fcf5da22a"),
                        CustomerCode = "CUST-001",
                        CustomerName = "John Doe"
                    },
                    new
                    {
                        Id = new Guid("0c30022b-8617-47ec-8e2d-6f327f507084"),
                        CustomerCode = "CUST-002",
                        CustomerName = "Jane Smith"
                    });
            });
#pragma warning restore 612, 618
    }
}