name: Build and Upload .NET App to S3

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1  # Change to your AWS region
      DOTNET_VERSION: '8.0.x'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore src/Yourdrs.Reports.API/Yourdrs.Reports.API.csproj  # Update path if necessary

      - name: Build
        run: dotnet build src/Yourdrs.Reports.API/Yourdrs.Reports.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/Yourdrs.Reports.API/Yourdrs.Reports.API.csproj -c Release -o publish

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Upload to S3
      #   run: |
      #     aws s3 sync ./publish s3://your-bucket-name/path-to-deploy/ --delete
